insert into localizacao(endereco, valor) values ('Rua Jorge Brito, 500 - Alves Castro', 500.99);
insert into localizacao(endereco, valor) values ('Avenida das Indias, 750 - Catuape', 1000.00);
insert into localizacao(endereco, valor) values ('Rua Serra de Pija, 230 - Catuape', 12000.00);
insert into localizacao(endereco, valor) values ('Avenida Conde de Botoraí, 5458- Dimgomes', 450.00);

insert into pessoas(nome, idade, sexo) values ('Jorge Amadeu Britto', 25, '1'); 
insert into pessoas(nome, idade, sexo) values ('Janaina Petusk Pontes', 45, '0'); 
insert into pessoas(nome, idade, sexo) values ('Lorena Julya Almeida', 19, '0'); 
insert into pessoas(nome, idade, sexo) values ('Trianda Souza Felides', 26, '1'); 
insert into pessoas(nome, idade, sexo) values ('Marcelly Filha de Cabral', 65, '0'); 
insert into pessoas(nome, idade, sexo) values ('Alexandre Fernandes Pinto', 47, '1'); 
insert into pessoas(nome, idade, sexo) values ('Ketlleyn Portugal', 29, '0'); 
insert into pessoas(nome, idade, sexo) values ('João Marcelo Junior', 17, '1'); 
insert into pessoas(nome, idade, sexo) values ('Larissa Marcel Dantas', 27, '0'); 
insert into pessoas(nome, idade, sexo) values ('Lucas Pires Tolentinho', 23, '1'); 
insert into pessoas(nome, idade, sexo) values ('Sarah Solano Reis', 24, '0'); 
insert into pessoas(nome, idade, sexo) values ('Lorelai Gil Brant', 55, '0'); 
insert into pessoas(nome, idade, sexo) values ('Ricardo Jor Ilo', 47, '1'); 
insert into pessoas(nome, idade, sexo) values ('Ulisses Lopes Silva', 35, '1'); 
insert into pessoas(nome, idade, sexo) values ('Aline Tiara Miranda', 24, '0'); 
insert into pessoas(nome, idade, sexo) values ('Rui Bartolomeu', 33, '1'); 
insert into pessoas(nome, idade, sexo) values ('Valentina Patricia Kourtney', 30, '0'); 
insert into pessoas(nome, idade, sexo) values ('Romeu Yashu Hi', 68, '1'); 
insert into pessoas(nome, idade, sexo) values ('Yasmin Rodrigues', 45, '0'); 
insert into pessoas(nome, idade, sexo) values ('Wellignton Freire Ruas', 24, '1');

insert into evento(nome, edicao, tema, valorinscricao, fk_localizacao_id) values ('SSI', 1, 'Semana de Sistemas de Informação', 25.5, 1);
insert into evento(nome, edicao, tema, valorinscricao, fk_localizacao_id) values ('Encontro de pesquisadores', 5, 'Pesquisa científica', 50.25, 28);
insert into evento(nome, edicao, tema, valorinscricao, fk_localizacao_id) values ('SGPP', 7, 'Semana de gestão de políticas públicas', 2.5, 29);
insert into evento(nome, edicao, tema, valorinscricao, fk_localizacao_id) values ('SMKT', 10, 'Semana de marketing', 100.99, 30);
insert into evento(nome, edicao, tema, valorinscricao, fk_localizacao_id) values ('SCN', 1, 'Semana de Ciências da Natureza', 5.60, 31);
